# Generated by Django 3.0.8 on 2020-08-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_option',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10),
            preserve_default=False,
        ),
    ]
