# Generated by Django 3.0.8 on 2020-08-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200801_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Option',
            new_name='ProductOption',
        ),
    ]
