# Generated by Django 3.0.8 on 2020-08-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200801_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
