# Generated by Django 3.0.8 on 2020-08-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200802_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
